class Config:
	SECRET_KEY = 'lNKHKcggvsuIOlUprbzqOvXPXXhsgliAekKJcMLxhwXsLbTefbMsiPGOitwnWBoVwkcflcfZTGYFLMCtjqsIBDFkfJuzaOtwKOeNZQmoiLWWbhUUJMMkgyRXoYdTfOcEiXlGKbxEDRQZmtJPExOrOQFHOpqtBnBeIZIAzzdabSVPtEpoIYjwpkBLDMrbiclunqrfnVCnUieCxoQSUkVTbnJuHIbigRmyPXGCQKBiXgLWJTZhlUlJLSFhffxkpJqj'
