"""empty message

Revision ID: 556171436e5f
Revises: 75e84efbcd93
Create Date: 2023-04-04 15:10:33.134250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556171436e5f'
down_revision = '75e84efbcd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
