"""empty message

Revision ID: 75e84efbcd93
Revises: dcebf32e906e
Create Date: 2023-04-04 15:09:03.779287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e84efbcd93'
down_revision = 'dcebf32e906e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour_rate', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('hour_rate')

    # ### end Alembic commands ###
