"""empty message

Revision ID: a9cbbeffdc81
Revises: a5cf13b4b469
Create Date: 2023-05-13 20:37:55.942815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cbbeffdc81'
down_revision = 'a5cf13b4b469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment_tasks', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
